# Install dependencies
install:
	npm install

# Build the project
build:
	npm run build

# Link the package globally (makes 'staticstripes' command available)
link:
	npm link

# Unlink the package globally (removes 'staticstripes' command)
unlink:
	npm unlink -g

bl:
	make build
	make unlink
	make link
